export const SESSION_MAX_AGE_MS = 1000 * 60 * 30;
export const SESSION_MAX_AGE_SECONDS = SESSION_MAX_AGE_MS / 1000;

export const SESSION_REFRESH_COOKIE_NAME = 'l_session_refresh';
export const SESSION_REFRESH_MAX_AGE_MS = 1000 * 60 * 60 * 24 * 7;
export const SESSION_REFRESH_MAX_AGE_SECONDS = SESSION_REFRESH_MAX_AGE_MS / 1000;
