export const SESSION_MAX_AGE_MS = 1000 * 60 * 30;
export const SESSION_MAX_AGE_SECONDS = SESSION_MAX_AGE_MS / 1000;

export const SILENT_SIGN_IN_COOKIE_NAME = 'accountId';
export const SILENT_SIGN_IN_MAX_AGE_MS = 1000 * 60 * 60 * 24 * 7;
export const SILENT_SIGN_IN_MAX_AGE_SECONDS = SILENT_SIGN_IN_MAX_AGE_MS / 1000;
