# This configuration is for the local development environment.

version: '3.8'

services:
  dynamodb:
    command: '-jar DynamoDBLocal.jar -sharedDb -dbPath ./data'
    image: 'amazon/dynamodb-local:latest'
    container_name: dynamodb-local
    ports:
      - '8000:8000'
    volumes:
      - './data/dynamodb:/home/dynamodblocal/data'
    user: 'root'

  dynamodb-admin:
    image: 'aaronshaf/dynamodb-admin'
    ports:
      - '8001:8001'
    environment:
      AWS_ACCESS_KEY_ID: 'local'
      AWS_REGION: 'ap-northeast-2'
      AWS_SECRET_ACCESS_KEY: 'local'
      DYNAMO_ENDPOINT: 'http://dynamodb-local:8000'
    depends_on:
      - dynamodb

  rds:
    build: './postgres'
    container_name: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - './data/postgres:/var/lib/postgresql/data'

  redis:
    image: redis:7.0
    command:
      - /bin/sh
      - -c
      - redis-server --requirepass redis
    container_name: redis
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - './data/redis:/data'
