# This configuration is for the local development environment.

version: '3.8'

services:
  rds:
    build: './postgres'
    container_name: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'

  redis:
    image: redis:7.0
    command:
      - /bin/sh
      - -c
      - redis-server --requirepass redis
    container_name: redis
    restart: always
    ports:
      - '6379:6379'
