# This configuration is for the local development environment.

version: '3.8'

services:
  localstack:
    image: localstack/localstack:1.3
    container_name: localstack
    restart: always
    ports:
      - 4566:4566
    volumes:
      - './data/localstack:/var/lib/localstack'

  mongo:
    image: mongo:5.0
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: admin
    ports:
      - 27017:27017
    volumes:
      - ./data/mongo:/data/db
      - ./mongo/init:/docker-entrypoint-initdb.d

  mongo-express:
    image: mongo-express:0.54
    container_name: mongo-admin
    restart: always
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_URL: mongodb://root:root@mongo:27017/?authSource=admin
    links:
      - mongo
    ports:
      - 8081:8081

  rds:
    build: './postgres'
    container_name: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - './data/postgres:/var/lib/postgresql/data'

  redis:
    image: redis:7.0
    command:
      - /bin/sh
      - -c
      - redis-server --requirepass redis
    container_name: redis
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - './data/redis:/data'
